# dumps the Android logs from the given step(s)

parameters:
- name: steps
  type: stepList

steps:
- task: CmdLine@2
  inputs:
    script: |
      python3 tools/python/run_adb.py logcat --clear || exit 0
  displayName: "Clear Android logs"
  condition: succeededOrFailed()

- ${{ parameters.steps }}

- task: CmdLine@2
  inputs:
    script: |
      python3 tools/python/run_adb.py logcat -d || exit 0
  displayName: "Dump Android logs"
  condition: succeededOrFailed()
