# Install appcenter CLI

parameters:
- name: appcenterVersion
  type: string
  default: "2.17.3"

steps:
- bash: |
    set -e -x
    npm install -g appcenter-cli@${{ parameters.appcenterVersion }}
  displayName: Install appcenter CLI ${{ parameters.appcenterVersion }}
