parameters:
- name: GradleWrapperVersion
  type: string
  default: "8.0.1"

steps:
- script: |
    gradle wrapper --gradle-version="${{ parameters.GradleWrapperVersion }}" --no-daemon --no-watch-fs
  displayName: Set up gradle ${{ parameters.GradleWrapperVersion }} wrapper
  workingDirectory: $(Build.SourcesDirectory)/java
