# steps in this build:
# 1a. Android minimal baseline build (arm64-v8a, including no kernels, with exceptions disabled)
# 1b. Android minimal baseline build with debug info

parameters:
- name: DoBuildWithDebugInfo
  displayName: Create additional build with debug information?
  type: boolean
  default: false

resources:
  repositories:
  - repository: manylinux
    type: Github
    endpoint: Microsoft
    name: pypa/manylinux
    ref: 1a61614cabfd6b91c6afd6d9e172cc5b838c65fe

jobs:
- job: BinarySizeChecks
  timeoutInMinutes: 30
  workspace:
    clean: all
  pool: Linux-CPU-2019

  strategy:
    matrix:
      AndroidMinimalBaseline:
        ConfigId: minimal-baseline
        BuildConfigFile: "/onnxruntime_src/tools/ci_build/github/linux/ort_minimal/build_check_binsize_config/android_minimal_baseline.config"
        BinarySizeThresholdInBytes: 1306224
      AndroidMinimalBasicWithOps:
        ConfigId: android-minimal-basic-with-some-ops
        BuildConfigFile: "/onnxruntime_src/tools/ci_build/github/linux/ort_minimal/build_check_binsize_config/android_minimal_basic_with_some_ops.config"
        BinarySizeThresholdInBytes: 1306224

  steps:
  - checkout: self
    clean: true
    submodules: recursive

  - template: templates/get-docker-image-steps.yml
    parameters:
      Dockerfile: tools/ci_build/github/linux/docker/Dockerfile.manylinux2014_cpu
      Context: tools/ci_build/github/linux/docker
      DockerBuildArgs: "--build-arg BUILD_UID=$( id -u )"
      Repository: onnxruntimecpubuild

  - task: CmdLine@2
    displayName: 1a. Build onnxruntime
    inputs:
      script: |
        NDK_HOME=$(realpath $ANDROID_NDK_HOME)
        docker run --rm \
          --volume $(Build.SourcesDirectory):/onnxruntime_src \
          --volume $(Build.BinariesDirectory):/build \
          --volume $ANDROID_HOME:/android_home \
          --volume $NDK_HOME:/ndk_home \
          -e ALLOW_RELEASED_ONNX_OPSET_ONLY=1 \
          -e NIGHTLY_BUILD \
          -e BUILD_BUILDNUMBER \
          -e BUILD_SOURCEVERSION=$(Build.SourceVersion) \
          -e BUILD_ID=$(Build.BuildId) \
          -e BUILD_REASON=$(Build.Reason) \
          -e BUILD_BRANCH=$(Build.SourceBranch) \
          onnxruntimecpubuild \
            /opt/python/cp37-cp37m/bin/python3 /onnxruntime_src/tools/ci_build/github/linux/ort_minimal/build_ort_and_check_binary_size.py \
              --build_dir /build/1a \
              --config_id $(ConfigId) \
              --threshold_size_in_bytes $(BinarySizeThresholdInBytes) \
              $(BuildConfigFile)
      workingDirectory: $(Build.SourcesDirectory)

  - task: AzureCLI@2
    displayName: 1a. Publish binary size data
    # only publish size data for CI builds on main
    condition: and(succeededOrFailed(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    inputs:
      azureSubscription: AIInfraBuild
      scriptLocation: inlineScript
      scriptType: bash
      inlineScript: |
        BINARY_SIZE_DATA_FILE="$(Build.BinariesDirectory)/1a/MinSizeRel/binary_size_data.txt"
        if [[ ! -f "${BINARY_SIZE_DATA_FILE}" ]]; then
          echo "File not found: ${BINARY_SIZE_DATA_FILE}"
          exit 1
        fi
        /usr/bin/python3 -m pip install -r $(Build.SourcesDirectory)/tools/ci_build/github/windows/post_to_dashboard/requirements.txt && \
        /usr/bin/python3 $(Build.SourcesDirectory)/tools/ci_build/github/windows/post_binary_sizes_to_dashboard.py \
          --commit_hash=$(Build.SourceVersion) \
          --size_data_file="${BINARY_SIZE_DATA_FILE}" \
          --build_project=onnxruntime \
          --build_id=$(Build.BuildId)
      workingDirectory: '$(Build.BinariesDirectory)'

  - task: PublishPipelineArtifact@1
    displayName: 1a. Publish binary artifact
    inputs:
      targetPath: $(Build.BinariesDirectory)/1a/MinSizeRel/libonnxruntime.so
      artifactName: $(ConfigId)-binary

  - ${{ if parameters.DoBuildWithDebugInfo }}:
    - task: CmdLine@2
      displayName: 1b. Build onnxruntime with debug info
      inputs:
        script: |
          NDK_HOME=$(realpath $ANDROID_NDK_HOME)
          docker run --rm \
            --volume $(Build.SourcesDirectory):/onnxruntime_src \
            --volume $(Build.BinariesDirectory):/build \
            --volume $ANDROID_HOME:/android_home \
            --volume $NDK_HOME:/ndk_home \
            -e ALLOW_RELEASED_ONNX_OPSET_ONLY=1 \
            -e NIGHTLY_BUILD \
            -e BUILD_BUILDNUMBER \
            -e BUILD_SOURCEVERSION=$(Build.SourceVersion) \
            -e BUILD_ID=$(Build.BuildId) \
            -e BUILD_REASON=$(Build.Reason) \
            -e BUILD_BRANCH=$(Build.SourceBranch) \
            onnxruntimecpubuild \
              /opt/python/cp37-cp37m/bin/python3 /onnxruntime_src/tools/ci_build/github/linux/ort_minimal/build_ort_and_check_binary_size.py \
                --build_dir /build/1b \
                --config_id $(ConfigId) \
                --with_debug_info \
                $(BuildConfigFile)
        workingDirectory: $(Build.SourcesDirectory)

    - task: PublishPipelineArtifact@1
      displayName: 1b. Publish binary artifact with debug info
      inputs:
        targetPath: $(Build.BinariesDirectory)/1b/MinSizeRel/libonnxruntime.so
        artifactName: $(ConfigId)-binary-with-debug-info

  - template: templates/clean-agent-build-directory-step.yml
