jobs:
- job: edch_test
  workspace:
    clean: all
  pool:
    vmImage: 'macOS-13'

  steps:
  - task: UsePythonVersion@0
    displayName: Use Python 3.10
    inputs:
      versionSpec: 3.10

  - task: JavaToolInstaller@0
    displayName: Use jdk 11
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - template: "templates/use-android-ndk.yml"

  - script: |
      python3 tools/python/run_android_emulator.py \
        --android-sdk-root ${ANDROID_SDK_ROOT} \
        --create-avd --system-image "system-images;android-31;default;x86_64" \
        --start --emulator-extra-args="-partition-size 4096 -verbose" \
        --emulator-pid-file $(Build.BinariesDirectory)/emulator.pid
    displayName: Start Android emulator
    timeoutInMinutes: 10

  - script: |
      python3 tools/python/run_android_emulator.py \
        --android-sdk-root ${ANDROID_SDK_ROOT} \
        --stop \
        --emulator-pid-file $(Build.BinariesDirectory)/emulator.pid
    displayName: Stop Android emulator
    condition: always()
