jobs:
- job: android_emulator_test
  workspace:
    clean: all
  pool:
    vmImage: 'macOS-13'

  steps:
  - checkout: none

  - bash: |
      set -e -x
      ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install 'system-images;android-31;default;x86_64'
      echo "no" | ${ANDROID_HOME}/cmdline-tools/latest/bin/avdmanager create avd --name android_emulator_avd --package 'system-images;android-31;default;x86_64' --force
      
      #${ANDROID_HOME}/tools/emulator -gpu guest -avd android_emulator_avd -perf-stat -no-snapshot -no-audio -no-boot-anim -camera-back none -camera-front none -cores 1 -qemu -m 2048 &
      # baseline
      ${ANDROID_HOME}/tools/emulator -avd android_emulator_avd -memory 4096 -timezone America/Los_Angeles -no-snapshot -no-audio -no-boot-anim -no-window
      
      ${ANDROID_HOME}/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
    displayName: Start Android emulator
    timeoutInMinutes: 10
