jobs:
- job: android_emulator_test
  workspace:
    clean: all
  pool:
    vmImage: 'macOS-12'

  steps:
  - checkout: none

  - task: UsePythonVersion@0
    displayName: Use Python 3.10
    inputs:
      versionSpec: 3.10

  - task: JavaToolInstaller@0
    displayName: Use jdk 11
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - bash: |
      set -e -x

      ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install 'system-images;android-31;default;x86_64'

      echo "no" | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/avdmanager create avd --name android_emulator_avd --package 'system-images;android-31;default;x86_64' --force

      ${ANDROID_SDK_ROOT}/tools/emulator \
        -avd android_emulator_avd \
        -memory 4096 \
        -timezone America/Los_Angeles \
        -no-snapshot -no-audio -no-boot-anim -no-window \
        -partition-size 4096 &

      ${ANDROID_SDK_ROOT}/platform-tools/adb wait-for-device shell 'while [[ -z \$(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'
    displayName: Start Android emulator
    timeoutInMinutes: 10
