jobs:
- job: j
  pool:
    vmImage: 'macOS-13'
  
  steps:
  - checkout: none
  - bash: |
      set -e -x

      XCODE_DEVELOPER_DIR="/Applications/Xcode_14.3.app/Contents/Developer"
      sudo xcode-select --switch "${XCODE_DEVELOPER_DIR}"

      xcrun simctl list --json -e
