jobs:
- job: iOS_App_Center_CI
  pool:
    vmImage: 'macOS-10.15'
  timeoutInMinutes: 60
  variables:
  - name: derived_data_path
    value: '$(build.BinariesDirectory)/DerivedData'
  steps:
    - task: InstallAppleCertificate@2
      displayName: 'Install ORT Mobile Test Signing Certificate'
      inputs:
        certSecureFile: '$(ios_signing_certificate_name)'
        certPwd: '$(ios_signing_certificate_password)'
        keychain: 'temp'
        deleteCert: true

    - task: InstallAppleProvisioningProfile@1
      displayName: 'Install ORT Mobile Test Provisioning Profile'
      inputs:
        provProfileSecureFile: '$(ios_provision_profile_name)'
        removeProfile: true

    - task: CocoaPods@0
      displayName: 'Install Pods'
      inputs:
        forceRepoUpdate: false
        workingDirectory: $(Build.SourcesDirectory)/onnxruntime/test/platform/ios/ios_package_test/

    - task: Xcode@5
      displayName: 'Build iphone arm64 tests'
      inputs:
        actions: 'build-for-testing'
        configuration: 'Debug'
        xcWorkspacePath: '$(Build.SourcesDirectory)/onnxruntime/test/platform/ios/ios_package_test/ios_package_test.xcworkspace'
        sdk: 'iphoneos'
        scheme: 'ios_package_test'
        signingOption: 'manual'
        signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
        provisioningProfileName: 'iOS Team Provisioning Profile'
        args: '-derivedDataPath $(derived_data_path)'
        workingDirectory: $(Build.SourcesDirectory)/onnxruntime/test/platform/ios/ios_package_test/

    - script: |
        set -e -x
        appcenter test run xcuitest \
          --app "AI-Frameworks/ORT-Mobile-iOS" \
          --devices $(app_center_test_devices) \
          --test-series "master" \
          --locale "en_US" \
          --build-dir $(derived_data_path)/Build/Products/Debug-iphoneos \
          --token $(app_center_api_token)
      displayName: Run E2E tests on App Center
