jobs:
- job: iOS_App_Center_CI
  pool:
    vmImage: 'macOS-10.15'
  timeoutInMinutes: 60
  steps:
    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: '$(certName)'
        certPwd: '$(certPwd)'
        keychain: 'temp'
        deleteCert: true

    - task: CocoaPods@0
      inputs:
        forceRepoUpdate: false
        workingDirectory: $(Build.SourcesDirectory)/onnxruntime/test/platform/ios/ios_package_test/

    # - script: |
    #     cd $(Build.SourcesDirectory)/onnxruntime/test/platform/ios/ios_package_test/
    #     xcrun xcodebuild test \
    #       -workspace ./ios_package_test.xcworkspace \
    #       -scheme ios_package_test \
    #       -destination 'platform=iOS Simulator,OS=latest,name=iPhone SE (2nd generation)'

    - task: Xcode@5
      inputs:
        actions: 'build-for-testing'
        configuration: 'Debug'
        xcWorkspacePath: 'ios_package_test.xcworkspace'
        sdk: 'iphonesimulator'
        scheme: 'ios_package_test'
        workingDirectory: $(Build.SourcesDirectory)/onnxruntime/test/platform/ios/ios_package_test/

    # - task: Xcode@5
    #   inputs:
    #     actions: 'build-for-testing'
    #     configuration: 'Debug'
    #     workspace: './ios_package_test.xcworkspace'
    #     sdk: 'iphoneos'
    #     scheme: 'ios_package_test'
    #     signingOption: 'manual'
    #     signingIdentity: 'Apple Development: Guoyu Wang (69VJ8CLFPM)'
    #     args: '-derivedDataPath $(build.BinariesDirectory)/DerivedData'
    #     workingDirectory: $(Build.SourcesDirectory)/onnxruntime/test/platform/ios/ios_package_test/

  # - script: |
  #     cd $(Build.SourcesDirectory)/java/src/test/android
  #     appcenter test run espresso \
  #       --app "gwang-05tf/AppCenter-Espresso-E2E-Example" \
  #       --devices 581708da \
  #       --app-path ./app/build/outputs/apk/debug/app-debug.apk \
  #       --test-series "master" \
  #       --locale "en_US" \
  #       --build-dir ./app/build/outputs/apk/androidTest/debug \
  #       --token $(AppCenterAPIToken)
  #   workingDirectory: $(Build.BinariesDirectory)
  #   displayName: Run E2E tests on App Center
