jobs:
- job: iOS_App_Center_CI
  pool:
    vmImage: 'macOS-10.15'
  timeoutInMinutes: 60
  steps:
    - task: InstallAppleCertificate@2
      displayName: 'Install ORT Mobile Test Signing Certificate'
      inputs:
        certSecureFile: '$(certName)'
        certPwd: '$(certPwd)'
        keychain: 'temp'
        deleteCert: true

    - task: InstallAppleProvisioningProfile@1
      displayName: 'Install ORT Mobile Test Provisioning Profile'
      inputs:
        provProfileSecureFile: 'iOS_Team_Provisioning_Profile.mobileprovision'

    - task: CocoaPods@0
      displayName: 'Install Pods'
      inputs:
        forceRepoUpdate: false
        workingDirectory: $(Build.SourcesDirectory)/onnxruntime/test/platform/ios/ios_package_test/

    # - script: |
    #     cd $(Build.SourcesDirectory)/onnxruntime/test/platform/ios/ios_package_test/
    #     xcrun xcodebuild test \
    #       -workspace ./ios_package_test.xcworkspace \
    #       -scheme ios_package_test \
    #       -destination 'platform=iOS Simulator,OS=latest,name=iPhone SE (2nd generation)'

    # - task: Xcode@5
    #   inputs:
    #     actions: 'build-for-testing'
    #     configuration: 'Debug'
    #     xcWorkspacePath: '$(Build.SourcesDirectory)/onnxruntime/test/platform/ios/ios_package_test/ios_package_test.xcworkspace'
    #     sdk: 'iphonesimulator'
    #     scheme: 'ios_package_test'
    #     workingDirectory: $(Build.SourcesDirectory)/onnxruntime/test/platform/ios/ios_package_test/

    - task: Xcode@5
      displayName: 'Build iphone arm64 tests'
      inputs:
        actions: 'build-for-testing'
        configuration: 'Debug'
        xcWorkspacePath: '$(Build.SourcesDirectory)/onnxruntime/test/platform/ios/ios_package_test/ios_package_test.xcworkspace'
        sdk: 'iphoneos'
        scheme: 'ios_package_test'
        signingOption: 'manual'
        signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
        provisioningProfileName: 'iOS Team Provisioning Profile'
        args: '-derivedDataPath $(build.BinariesDirectory)/DerivedData'
        workingDirectory: $(Build.SourcesDirectory)/onnxruntime/test/platform/ios/ios_package_test/

    - script: |
        set -e -x
        cd $(Build.SourcesDirectory)/java/src/test/android
        appcenter test run xcuitest \
          --app "gwang-05tf/ObjC_iOS_Test" \
          --devices bb484696 \
          --test-series "master" \
          --locale "en_US" \
          --build-dir $(build.BinariesDirectory)/DerivedData/Build/Products/Debug-iphoneos \
          --token $(AppCenterAPIToken)
      workingDirectory: $(Build.SourcesDirectory)/java/src/test/android
      displayName: Run E2E tests on App Center
