jobs:
- job: 'Sign_OV_Files'
  workspace:
    clean: all
  timeoutInMinutes: 3000
  pool: 'onnxruntime-gpu-winbuild'
  
  steps:
    - script: 'curl https://github.com/intel/onnxruntime/releases/download/v4.0/cpu_binaries_uep_v4.0.zip'
      displayName: 'get zip file'
      workingDirectory: '$(Build.ArtifactStagingDirectory)/'
    
    - script: 'unzip cpu_binaries_uep_v4.0.zip'
      displayName: 'unzip zip file'
      workingDirectory: '$(Build.ArtifactStagingDirectory)/'
      
    - template: templates/esrp_nuget.yml
      parameters:
        DisplayName: 'ESRP - sign NuGet package'
        FolderPath: '$(Build.ArtifactStagingDirectory)/'
        DoEsrp: 'true'
        
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'cpu binaries'
        
    - template: templates/component-governance-component-detection-steps.yml
      parameters :
        condition : 'succeeded'
        
    - template: templates/clean-agent-build-directory-step.yml
