jobs:
- job: Linux_Build
  timeoutInMinutes: 120
  workspace:
    clean: all
  pool: Linux-CPU-2019
  steps:
  - script: |
    workingDirectory: '$(Build.SourcesDirectory)'
    displayName: 'dummpy step'