jobs:
- job: build
  workspace:
    clean: all
  timeoutInMinutes:  120
  pool: 'Onnxruntime-Linux-GPU-TensorRT-Perf'
  variables:
  - name: PoolName
    value: 'Testing on Pool'
  steps:
    - script: 'docker images'
      displayName: 'sample test'
      
    - template: templates/clean-agent-build-directory-step.yml
