jobs:
- job: Linux_Build
  timeoutInMinutes: 120
  workspace:
    clean: all
  pool: Linux-CPU-2019
  steps:
  - checkout: self
    clean: true
    submodules: recursive

  - task: NodeTool@0
    inputs:
      versionSpec: '12.16.3'

  - template: templates/get-docker-image-steps.yml
    parameters:
      Dockerfile: tools/ci_build/github/linux/docker/Dockerfile.manylinux2014_lort_cpu
      Context: tools/ci_build/github/linux/docker
      DockerBuildArgs: "--build-arg BUILD_UID=$( id -u )"
      Repository: onnxruntimecpubuildlort

  - task: CmdLine@2
    displayName: 'Build ORT for Python 3.9'
    inputs:
      script: |
        docker run --rm \
          --volume $(Build.SourcesDirectory):/onnxruntime_src \
          --volume $(Build.BinariesDirectory):/build \
          -e ALLOW_RELEASED_ONNX_OPSET_ONLY=0 \
          -e NIGHTLY_BUILD \
          -e BUILD_BUILDNUMBER \
          onnxruntimecpubuildlort \
            /opt/python/cp39-cp39/bin/python3.9 /onnxruntime_src/tools/ci_build/build.py \
              --build_dir /build --cmake_generator Ninja \
              --config Release \
              --skip_submodule_sync \
              --build_shared_lib \
              --parallel \
              --enable_lazy_tensor --enable_training --build_wheel --skip_test \
      workingDirectory: $(Build.SourcesDirectory)

  - task: CmdLine@2
    displayName: 'Test LORT with Python 3.9'
    inputs:
      script: |
        docker run --rm \
          --volume $(Build.SourcesDirectory):/onnxruntime_src \
          --volume $(Build.BinariesDirectory):/build \
          -e ALLOW_RELEASED_ONNX_OPSET_ONLY=0 \
          -e NIGHTLY_BUILD \
          -e BUILD_BUILDNUMBER \
          onnxruntimecpubuildlort \
            bash -c "
              export ORT_LT_CHECK_BASELINE=1 && \
              export PYTHONPATH=/build/Release && \
              /opt/python/cp39-cp39/bin/python3.9 -m pip install /build/Release/dist/*.whl && \
              /opt/python/cp39-cp39/bin/python3.9 /onnxruntime_src/orttraining/orttraining/test/python/orttraining_test_lort.py"
      workingDirectory: $(Build.SourcesDirectory)
      condition: succeededOrFailed()

  - template: templates/clean-agent-build-directory-step.yml
