stages:
- template: templates/mac-cpu-packaging-pipeline.yml
  parameters:
    AllowReleasedOpsetOnly: 0
    BuildForAllArchs: false
    AdditionalBuildFlags: --build_objc --enable_language_interop_ops --build_wheel --use_xcode --use_xnnpack
    WithCache: true
