resources:
  repositories:
  - repository: onnxruntime-inference-examples # The name used to reference this repository in the checkout step
    type: github
    endpoint: ort-examples
    name: microsoft/onnxruntime-inference-examples

jobs:
- job: IosBuildSample
  displayName: "iOS build sample"

  pool:
    vmImage: "macOS-12"

  steps:
  - checkout: self                           # due to checkout multiple repos, the root directory is $(Build.SourcesDirectory)/onnxruntime
    submodules: false

  - checkout: onnxruntime-inference-examples # due to checkout multiple repos, the root directory is $(Build.SourcesDirectory)/onnxruntime-inference-examples
    submodules: false

  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: '$(ios_signing_certificate_name)'
      certPwd: '$(ios_signing_certificate_password)'
      keychain: 'temp'
      deleteCert: true
    displayName: 'Install ORT Mobile Test Signing Certificate'

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provProfileSecureFile: '$(ios_provision_profile_name)'
      removeProfile: true
    displayName: 'Install ORT Mobile Test Provisioning Profile'

  - bash: dotnet --info

  - bash: |
      set -x -e
      # manually install a couple of things to try. the sln based restore installs maui-ios and maui-android
      dotnet workload install ios
      dotnet workload restore ./MauiVisionSample/MauiVisionSample.csproj
      # dotnet workload restore ./MauiVisionSample.sln
      # dotnet build ./MauiVisionSample.sln
      # try without the /p args first for another data point
      dotnet publish -f:net6.0-ios -c:Release -r:ios-arm64 --no-self-contained ./MauiVisionSample.sln
      # dotnet publish -f:net6.0-ios -c:Release -r:ios-arm64 --no-self-contained ./MauiVisionSample/MauiVisionSample.csproj
      # dotnet publish -f:net6.0-ios -c:Release /p:"ArchiveOnBuild=true;NullabilityInfoContextSupport=true" -r:ios-arm64 ./MauiVisionSample.sln
    workingDirectory: onnxruntime-inference-examples/mobile/examples/Maui/MauiVisionSample
