jobs:
- job: Linux_Build
  timeoutInMinutes: 120
  workspace:
    clean: all
  pool: Linux-CPU-2019
  strategy:
    parallel: 8
  steps:
  - checkout: none
  - script: |
      set -x -e
      docker image prune --all
      python3 -m pip uninstall -y onnxruntime-training
