jobs:
- job: Linux_Build
  timeoutInMinutes: 120
  workspace:
    clean: all
  pool: Linux-CPU-2019
  steps:
  - checkout: self
    clean: true
    submodules: recursive

  - task: CmdLine@2
    displayName: 'Docker build'
    inputs:
      script: |
        docker build --pull -t onnxruntime-ubuntu-eager \
        --build-arg BUILD_USER=onnxruntimedev \
        --build-arg BUILD_UID=$(id -u) \
        --build-arg OS_VERSION=20.04 \
        --build-arg PYTHON_VERSION=3.8 -f Dockerfile.ubuntu_eager_mode .
      workingDirectory: $(Build.SourcesDirectory)/tools/ci_build/github/linux/docker

  - task: CmdLine@2
    displayName: 'Create and start docker container'
    inputs:
      script: |
        docker run -it -d \
          --name external_custom_ops_container \
          --volume /data/onnx:/data/onnx:ro \
          --volume $(Build.SourcesDirectory):/onnxruntime_src \
          --volume $(Build.BinariesDirectory):/build \
          --volume $HOME/.onnx:/home/onnxruntimedev/.onnx \
          onnxruntime-ubuntu-eager \
          /bin/bash
      workingDirectory: $(Build.SourcesDirectory)    

  - task: CmdLine@2
    displayName: 'ONNXRuntime build'
    inputs:
      script: |
        mkdir -p $HOME/.onnx
        docker exec -t \
          -e ALLOW_RELEASED_ONNX_OPSET_ONLY=0 \
          -e NIGHTLY_BUILD \
          -e BUILD_BUILDNUMBER \
          external_custom_ops_container \
            /usr/bin/python3 /onnxruntime_src/tools/ci_build/build.py \
              --build_dir /build \
              --config Debug Release \
              --skip_submodule_sync \
              --build_shared_lib \
              --parallel \
              --build_eager_mode --enable_training --enable_pybind \
              --build_wheel \
              --skip_tests \
              --enable_external_custom_op_schemas
      workingDirectory: $(Build.SourcesDirectory)
    condition: succeededOrFailed() # ensure all tests are run
  
  - task: CmdLine@2
    displayName: 'Install Release python package'
    inputs:
      script: |
         rm -rf $(Build.BinariesDirectory)/Release/onnxruntime $(Build.BinariesDirectory)/Release/pybind11
         docker exec -t external_custom_ops_container \
            /bin/bash -c "/usr/bin/python3 -m pip install /build/Release/dist/*.whl" 
      workingDirectory: $(Build.BinariesDirectory)
  
  - task: CmdLine@2
    displayName: 'Install Pybind11'
    inputs:
      script: |
         docker exec -t \
          -w  /build/Debug/external_custom_ops \
          external_custom_ops_container \
          /usr/bin/python3 -m pip install pybind11
      workingDirectory: $(Build.BinariesDirectory)

  - task: CmdLine@2
    displayName: 'Build and Install custom ops python package'
    inputs:
      script: |
         docker exec -t \
          -w  /build/Debug/external_custom_ops \
          external_custom_ops_container \
          /usr/bin/python3 -m pip install .
      workingDirectory: $(Build.BinariesDirectory)

  - task: CmdLine@2
    displayName: 'Test using external custom op module'
    inputs:
      script: |
         docker exec -t \
          -w  /build/Debug/external_custom_ops \
          external_custom_ops_container \
          /usr/bin/python3 test.py
      workingDirectory: $(Build.BinariesDirectory)


  - task: CmdLine@2
    displayName: 'Install Debug python package'
    inputs:
      script: |
         rm -rf $(Build.BinariesDirectory)/Debug/onnxruntime $(Build.BinariesDirectory)/Debug/pybind11
         docker exec -t external_custom_ops_container \
            /bin/bash -c "/usr/bin/python3 -m pip install /build/Debug/dist/*.whl" 
      workingDirectory: $(Build.BinariesDirectory)

  - task: CmdLine@2
    displayName: 'Build and Install custom ops python package'
    inputs:
      script: |
         docker exec -t \
          -w  /build/Debug/external_custom_ops \
          external_custom_ops_container \
          /usr/bin/python3 -m pip install .
      workingDirectory: $(Build.BinariesDirectory)

  - task: CmdLine@2
    displayName: 'Test using external custom op module'
    inputs:
      script: |
         docker exec -t \
          -w  /build/Debug/external_custom_ops \
          external_custom_ops_container \
          /usr/bin/python3 test.py
      workingDirectory: $(Build.BinariesDirectory)

  - task: CmdLine@2
    displayName: 'ONNXRuntime build'
    inputs:
      script: |
        docker exec -t \
          external_custom_ops_container \
            /usr/bin/python3 /onnxruntime_src/tools/ci_build/build.py \
              --build_dir /build \
              --config Debug Release \
              --test
      workingDirectory: $(Build.SourcesDirectory)
    condition: succeededOrFailed() # ensure all tests are run

  - task: CmdLine@2
    displayName: 'Stop and remove docker container'
    inputs:
      script: |
         docker stop external_custom_ops_container
         docker rm external_custom_ops_container