stages:
- template: templates/mac-cpu-packaging-pipeline.yml
  parameters:
    AllowReleasedOpsetOnly: 0
    BuildForAllArchs: false
    AdditionalBuildFlags: --enable_training --build_objc --use_xcode
    WithCache: true
