stages:
- template: stages/mac-cpu-packaging-stages.yml
  parameters:
    AllowReleasedOpsetOnly: 0
    BuildForAllArchs: false
    AdditionalBuildFlags: --enable_training --build_objc
    WithCache: true
