trigger: none

jobs:
- template: templates/linux-ci.yml
  parameters:
    AgentPool : 'Linux-Single-GPU-V100'
    JobName: 'Onnxruntime_Linux_GPU_Training'
    SubmoduleCheckoutMode: 'recursive'
    RunDockerBuildArgs: >
      -o ubuntu18.04 -d gpu -r $(Build.BinariesDirectory)
      -x "
      --enable_training
      --config $(buildConfig)
      --use_cuda --cuda_version=11.1 --cuda_home=/usr/local/cuda-11.1 --cudnn_home=/usr/local/cuda-11.1
      --build_wheel
      --enable_nvtx_profile
      "
    DoNugetPack: 'false'
    ArtifactName: 'drop-linux'
    TimeoutInMinutes: 140
    # Enable unreleased onnx opsets in CI builds
    # This facilitates testing the implementation for the new opsets
    AllowReleasedOpsetOnly: '0'
    Strategy: 
      maxParallel: 2
      matrix:
        Debug:
          buildConfig: Debug
        Release:
          buildConfig: Release

