jobs:
- job: Upload
  workspace:
    clean: all
  pool: 'Win-CPU-2021'
  condition: succeeded()
  steps:
  - checkout: self
    submodules: false

  - task: DownloadPipelineArtifact@2
    displayName: 'Download Pipeline Artifact'
    inputs:
      buildType: specific
      project: '530acbc4-21bc-487d-8cd8-348ff451d2ff'
      definition: 845
      buildVersionToDownload: specific
      pipelineId: 150094
      artifactName: 'html'
      targetPath: '$(Build.BinariesDirectory)'
      
  - task: AzureFileCopy@4
    displayName: 'AzureBlob File Copy'
    inputs:
      SourcePath: '$(Build.BinariesDirectory)\*'
      azureSubscription: AIInfraBuildOnnxRuntimeOSS
      Destination: AzureBlob
      storage: onnxruntime
      ContainerName: '$web'