jobs:
- job: 'Sign_OV_Files'
  workspace:
    clean: all
  timeoutInMinutes: 15
  pool: 'onnxruntime-gpu-winbuild'
  
  steps:
    - task: DownloadSecureFile@1
      name: onnxruntimeDlls # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
      inputs:
        secureFile: '$(secureFile)'

    - script: 'mkdir $(Build.SourcesDirectory)\Artifact && copy $(onnxruntimeDlls.secureFilePath) $(Build.SourcesDirectory)\Artifact'
      displayName: 'Copy dlls to sources directory'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.SourcesDirectory)\Artifact'
        artifactName: 'Signed Dlls'
        
    - template: templates/clean-agent-build-directory-step.yml
