parameters:
- name: NpmPublish
  displayName: 'NPM packages publish configuration'
  type: string
  values:
  - 'nightly (@dev)'
  - 'release candidate (@rc)'
  - 'production (@latest)'
  - 'custom'
  default: 'nightly (@dev)'

- name: UseJspi
  displayName: 'Use JSPI based ASYNCIFY feature for WebAssembly build'
  type: boolean
  default: false

variables:
  # pipeline should define the following varaibles
  #   ExtraBuildArgs
  #   VersionSuffix

  ${{ if eq(parameters.NpmPublish, 'nightly (@dev)') }}:
    NpmPackagingMode: 'dev'
  ${{ if eq(parameters.NpmPublish, 'release candidate (@rc)') }}:
    NpmPackagingMode: 'rc'
  ${{ if eq(parameters.NpmPublish, 'production (@latest)') }}:
    NpmPackagingMode: 'release'
  ${{ if eq(parameters.NpmPublish, 'custom') }}:
    NpmPackagingMode: '$(VersionSuffix)'

stages:
- template: templates/web-ci.yml
  parameters:
    NpmPackagingMode: ${{ variables.NpmPackagingMode }}
    IsReleasePipeline: false
    PoolName: 'onnxruntime-Win-CPU-2022-web'
    BuildStaticLib: true
    ExtraBuildArgs: $(ExtraBuildArgs)
    UseJspi: ${{ parameters.UseJspi }}
