parameters:
- name: NpmPublish
  displayName: 'NPM packages publish configuration'
  type: string
  values:
  - 'nightly (@dev)'
  - 'release candidate (@rc)'
  - 'production (@latest)'
  - 'custom'
  default: 'nightly (@dev)'

variables:
  # pipeline should define the following varaibles
  #   ExtraBuildArgs
  #   VersionSuffix

  ${{ if eq(parameters.NpmPublish, 'nightly (@dev)') }}:
    NpmPackagingMode: 'dev'
  ${{ if eq(parameters.NpmPublish, 'release candidate (@rc)') }}:
    NpmPackagingMode: 'rc'
  ${{ if eq(parameters.NpmPublish, 'production (@latest)') }}:
    NpmPackagingMode: 'release'
  ${{ if eq(parameters.NpmPublish, 'custom') }}:
    NpmPackagingMode: '$(VersionSuffix)'

stages:
- template: stages/web-ci-stages.yml
  parameters:
    NpmPackagingMode: ${{ variables.NpmPackagingMode }}
    IsReleasePipeline: false
    PoolName: 'onnxruntime-Ubuntu2004-AMD-CPU'
    BuildStaticLib: true
    ExtraBuildArgs: $(ExtraBuildArgs)
    WASMTemplate: jobs/linux-wasm-ci-jobs.yml
    WebTemplate: jobs/win-web-ci-jobs.yml
    UseWebPoolName: true
    RunWebGpuTests: true
    WebGpuPoolName: 'onnxruntime-Win2022-webgpu-A10'
    WebCpuPoolName: 'onnxruntime-Win-CPU-2022-web'
    WithCache: true
