stages:
- stage: TensorRT_CI
  dependsOn: []
  jobs:
    - template: templates/jobs/win-ci-vs-2022-job.yml
      parameters:
        BuildConfig: 'RelWithDebInfo'
        EnvSetupScript: setup_env_trt.bat
        buildArch: x64
        additionalBuildFlags: --use_cuda --cuda_home="$(Agent.TempDirectory)\v11.8" --use_tensorrt --tensorrt_home="C:\local\TensorRT-8.6.1.6.Windows10.x86_64.cuda-11.8" --cuda_version=11.8 --cuda_home="$(Agent.TempDirectory)\v11.8"--cmake_extra_defines CMAKE_CUDA_ARCHITECTURES=75
        msbuildPlatform: x64
        isX86: false
        job_name_suffix: x64_RelWithDebInfo
        RunOnnxRuntimeTests: true
        RunStaticCodeAnalysis: false
        ORT_EP_NAME: TensorRT
        WITH_CACHE: true
        MachinePool: onnxruntime-Win2022-GPU-T4
