trigger: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Job

  steps:
  - checkout: none

  - script: |
      sleep 300 &
      echo $! >> pid.txt

  - script: |
      kill $( cat pid.txt )
