parameters:
- name: "value"
  type: "number"

trigger: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Job

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
      architecture: 'x64'

  - script: |
      python -m pip install mysql-connector-python
