trigger: none

pool:
  vmImage: 'macOS-10.15'

jobs:
- job: j0

  steps:
  - checkout: self
    submodules: false

  - script: |
      echo "Build.SourceVersion = $(Build.SourceVersion)"
      echo "git rev-parse HEAD = $(git rev-parse HEAD)"
      sleep 120

- job: j1
  dependsOn: j0

  steps:
  - checkout: self
    submodules: false

  - script: |
      echo "Build.SourceVersion = $(Build.SourceVersion)"
      echo "git rev-parse HEAD = $(git rev-parse HEAD)"
      sleep 120

- job: j2
  dependsOn: j1

  steps:
  - checkout: self
    submodules: false

  - script: |
      echo "Build.SourceVersion = $(Build.SourceVersion)"
      echo "git rev-parse HEAD = $(git rev-parse HEAD)"
      sleep 120

- job: j3
  dependsOn: j2

  steps:
  - checkout: self
    submodules: false

  - script: |
      echo "Build.SourceVersion = $(Build.SourceVersion)"
      echo "git rev-parse HEAD = $(git rev-parse HEAD)"
      sleep 120

- job: j4
  dependsOn: j3

  steps:
  - checkout: self
    submodules: false

  - script: |
      echo "Build.SourceVersion = $(Build.SourceVersion)"
      echo "git rev-parse HEAD = $(git rev-parse HEAD)"
      sleep 120