trigger: none

pool: 'Linux-CPU'

jobs:
- job: Job

  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'AIInfraBuildOnnxRuntimeOSS'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az --version'
