schedules:
- cron: "0 8 * * *"
  displayName: Daily Build
  branches:
    include:
    - master
  always: true

jobs: 
- template: templates/cpu-noopenmp.yml
  parameters:
    AgentPool : 'Win-CPU-2019'
    DoEsrp: 'true'
    DoCompliance: 'true'
