schedules:
- cron: "0 8 * * *"
  displayName: Daily Build
  branches:
    include:
    - master
  always: true

variables:
  PackageName: 'Microsoft.ML.OnnxRuntime.TensorRT'
  TESTONGPU: 'ON'

jobs: 
- template: templates/test_win.yml
  parameters:
    AgentPool : 'onnxruntime-gpu-winbuild'
    DoEsrp: 'true'
    SharedEps: TensorRT 
