parameters:
  JobSuffix: ''
stages:
- stage: Nodejs_Test_MacOS_${{ parameters.JobSuffix }}
  jobs:
  - job:
    workspace:
      clean: all
    timeoutInMinutes:  120
    pool:
      vmImage: 'macOS-12'
    dependsOn:
    - Nodejs_Packaging_CPU
    condition: succeeded()
    variables:
    - name: OnnxRuntimeBuildDirectory
      value: '$(Build.BinariesDirectory)'
    steps:
    - template: test.yml
