parameters:
  AgentPool: 'Linux-CPU'
  JobSuffix: ''
stages:
- stage: Nodejs_Test_${{ parameters.JobSuffix }}
  dependsOn:
  - Nodejs_Packaging_CPU
  condition: succeeded()
  jobs:
  - job:
    workspace:
      clean: all
    timeoutInMinutes:  120
    pool: ${{ parameters.AgentPool }}

    variables:
    - name: OnnxRuntimeBuildDirectory
      value: '$(Build.BinariesDirectory)'
    steps:
    - template: test.yml
  