parameters:
  AgentPool: 'Linux-CPU'
  JobSuffix: ''
stages:
- stage: Nodejs_Test_${{ parameters.JobSuffix }}
  jobs:
  - job:
    workspace:
      clean: all
    timeoutInMinutes:  120
    pool: ${{ parameters.AgentPool }}
    dependsOn:
    - Nodejs_Packaging_CPU
    condition: succeeded()
    variables:
    - name: OnnxRuntimeBuildDirectory
      value: '$(Build.BinariesDirectory)'
    steps:
    - template: test.yml
  