parameters:
- name: EnvSetupScript
  type: string

- name: BuildConfig
  type: string

- name: BuildArch
  type: string

- name: DownloadCUDA
  type: boolean
  default: false

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true
    architecture: ${{parameters.BuildArch}}

- script: |
    python -m pip install -q setuptools wheel numpy
  workingDirectory: '$(Build.BinariesDirectory)'
  displayName: 'Install python modules'

- template: ../download-deps.yml

- task: PythonScript@0
  displayName: 'Update deps.txt'
  inputs:
    scriptPath: $(Build.SourcesDirectory)/tools/ci_build/replace_urls_in_deps.py
    arguments: --new_dir $(Build.BinariesDirectory)/deps
    workingDirectory: $(Build.BinariesDirectory)

- template: set-winenv.yml
  parameters:
    EnvSetupScript: ${{parameters.EnvSetupScript}}
    DownloadCUDA: ${{parameters.DownloadCUDA}}

- task: PowerShell@2
  displayName: 'Install ONNX'
  inputs:
    filePath: '$(Build.SourcesDirectory)/tools/ci_build/github/windows/install_third_party_deps.ps1'
    workingDirectory: '$(Build.BinariesDirectory)'
    arguments: -cpu_arch x64 -install_prefix $(Build.BinariesDirectory)\${{parameters.BuildConfig}}\installed -build_config ${{parameters.BuildConfig}}
